# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\untitled3.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import datetime

now = datetime.datetime.now()
year = now.year
month = now.month
day = now.day
print(year,month,day)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(547, 766)
        Dialog.setMinimumSize(QtCore.QSize(547, 659))
        #Dialog.setSizeGripEnabled(True)
        self.Drivers = QtWidgets.QTabWidget(Dialog)
        self.Drivers.setGeometry(QtCore.QRect(10, 70, 531, 581))
        self.Drivers.setObjectName("Drivers")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.listWidget = QtWidgets.QListWidget(self.tab)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 521, 561))
        self.listWidget.setObjectName("listWidget")
        self.Drivers.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.listWidget_2 = QtWidgets.QListWidget(self.tab_2)
        self.listWidget_2.setGeometry(QtCore.QRect(0, 0, 521, 521))
        self.listWidget_2.setObjectName("listWidget_2")
        self.pB_accept = QtWidgets.QPushButton(self.tab_2)
        self.pB_accept.setGeometry(QtCore.QRect(10, 530, 75, 23))
        self.pB_accept.setObjectName("pB_accept")
        self.pB_accept_2 = QtWidgets.QPushButton(self.tab_2)
        self.pB_accept_2.setGeometry(QtCore.QRect(440, 530, 75, 23))
        self.pB_accept_2.setObjectName("pB_accept_2")
        self.Drivers.addTab(self.tab_2, "")
        self.pB_print = QtWidgets.QPushButton(Dialog)
        self.pB_print.setGeometry(QtCore.QRect(20, 730, 75, 23))
        self.pB_print.setObjectName("pB_print")
        self.dateFrom = QtWidgets.QDateEdit(Dialog)
        self.dateFrom.setGeometry(QtCore.QRect(9, 10, 91, 20))
        self.dateFrom.setMinimumSize(QtCore.QSize(91, 0))
        self.dateFrom.setMaximumSize(QtCore.QSize(91, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.dateFrom.setFont(font)
        self.dateFrom.setMouseTracking(True)
        self.dateFrom.setTabletTracking(False)
        self.dateFrom.setDateTime(QtCore.QDateTime(QtCore.QDate(year, month, day), QtCore.QTime(16, 0, 0))) # changed date time
        self.dateFrom.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2049, 12, 29), QtCore.QTime(16, 0, 0)))
        self.dateFrom.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2014, 12, 31), QtCore.QTime(16, 0, 0)))
        self.dateFrom.setMaximumDate(QtCore.QDate(2049, 12, 29))
        self.dateFrom.setMaximumTime(QtCore.QTime(16, 0, 0))
        self.dateFrom.setMinimumTime(QtCore.QTime(16, 0, 0))
        self.dateFrom.setCalendarPopup(True)
        self.dateFrom.setTimeSpec(QtCore.Qt.UTC)
        self.dateFrom.setDate(QtCore.QDate(year, month, day)) # changed date time
        self.dateFrom.setObjectName("dateFrom")
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(240, 10, 91, 17))
        self.checkBox.setObjectName("checkBox")
        self.pB_download = QtWidgets.QPushButton(Dialog)
        self.pB_download.setGeometry(QtCore.QRect(390, 10, 75, 23))
        self.pB_download.setObjectName("pB_download")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 660, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(30, 690, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 40, 501, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pB_Settings = QtWidgets.QToolButton(Dialog)
        self.pB_Settings.setGeometry(QtCore.QRect(510, 10, 25, 19))
        self.pB_Settings.setObjectName("pB_Settings")
        self.dateTo = QtWidgets.QDateEdit(Dialog)
        self.dateTo.setGeometry(QtCore.QRect(120, 10, 91, 20))
        self.dateTo.setMinimumSize(QtCore.QSize(91, 0))
        self.dateTo.setMaximumSize(QtCore.QSize(91, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.dateTo.setFont(font)
        self.dateTo.setMouseTracking(True)
        self.dateTo.setTabletTracking(False)
        self.dateTo.setDateTime(QtCore.QDateTime(QtCore.QDate(year, month, day), QtCore.QTime(16, 0, 0))) # changed date time
        self.dateTo.setTime(QtCore.QTime(16, 0, 0))
        self.dateTo.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2049, 12, 30), QtCore.QTime(16, 0, 0)))
        self.dateTo.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2014, 12, 31), QtCore.QTime(16, 0, 0)))
        self.dateTo.setMaximumDate(QtCore.QDate(2049, 12, 30))
        self.dateTo.setMinimumDate(QtCore.QDate(2014, 12, 31))
        self.dateTo.setMaximumTime(QtCore.QTime(16, 0, 0))
        self.dateTo.setMinimumTime(QtCore.QTime(16, 0, 0))
        self.dateTo.setCalendarPopup(True)
        self.dateTo.setTimeSpec(QtCore.Qt.UTC)
        self.dateTo.setDate(QtCore.QDate(year, month, day)) # changed date time
        self.dateTo.setObjectName("dateTo")
        self.Drivers.raise_()
        self.pB_print.raise_()
        self.checkBox.raise_()
        self.pB_download.raise_()
        self.label_4.raise_()
        self.label_6.raise_()
        self.label_5.raise_()
        self.pB_Settings.raise_()
        self.dateFrom.raise_()
        self.dateTo.raise_()

        self.retranslateUi(Dialog)
        self.Drivers.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Путевой лист v0.1"))
        self.Drivers.setTabText(self.Drivers.indexOf(self.tab), _translate("Dialog", "Машины"))
        self.pB_accept.setText(_translate("Dialog", "Привязать"))
        self.pB_accept_2.setText(_translate("Dialog", "Добавить"))
        self.Drivers.setTabText(self.Drivers.indexOf(self.tab_2), _translate("Dialog", "Водители"))
        self.pB_print.setText(_translate("Dialog", "Печать"))
        self.checkBox.setText(_translate("Dialog", "Показать все"))
        self.pB_download.setText(_translate("Dialog", "Загрузить"))
        self.label_4.setText(_translate("Dialog", "Машина"))
        self.label_6.setText(_translate("Dialog", "Водитель"))
        self.label_5.setText(_translate("Dialog", "Выберите машину и водителя"))
        self.pB_Settings.setText(_translate("Dialog", "Н"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
